#!/usr/bin/env bash
# =============================================================================
# SETUP PRE-COMMIT HOOK FOR SVG-PLE AUTO-SYNC
# =============================================================================
# Purpose: Install pre-commit hook to auto-sync svg-ple-todo.md on commit
# Usage: ./infra/scripts/setup-pre-commit-hook.sh
# =============================================================================

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
HOOK_FILE="$REPO_ROOT/.git/hooks/pre-commit"
SCRIPT_PATH="infra/scripts/auto-sync-svg-ple-github.sh"

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Setup Pre-Commit Hook — SVG-PLE Auto-Sync${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Check if we're in a git repository
if [ ! -d "$REPO_ROOT/.git" ]; then
    echo -e "${RED}❌ ERROR: Not in a git repository${NC}"
    exit 1
fi

# Check if auto-sync script exists
if [ ! -f "$REPO_ROOT/$SCRIPT_PATH" ]; then
    echo -e "${RED}❌ ERROR: Auto-sync script not found: $SCRIPT_PATH${NC}"
    exit 1
fi

# Create hooks directory if it doesn't exist
mkdir -p "$REPO_ROOT/.git/hooks"

# Check if pre-commit hook already exists
if [ -f "$HOOK_FILE" ]; then
    echo -e "${YELLOW}⚠️  Pre-commit hook already exists${NC}"
    echo ""
    echo "Current content:"
    echo "───────────────────────────────────────────────────────────"
    cat "$HOOK_FILE"
    echo "───────────────────────────────────────────────────────────"
    echo ""
    read -p "Append SVG-PLE sync to existing hook? [y/N] " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Append to existing hook
        cat >> "$HOOK_FILE" <<'HOOK_CONTENT'

# SVG-PLE To-Do Auto-Sync
echo "🔄 Syncing SVG-PLE To-Do with GitHub Projects..."
if [ -f "infra/scripts/auto-sync-svg-ple-github.sh" ]; then
    ./infra/scripts/auto-sync-svg-ple-github.sh --once || {
        echo "⚠️  SVG-PLE sync failed (non-blocking)"
    }
else
    echo "⚠️  Auto-sync script not found (skipping)"
fi
HOOK_CONTENT
        echo -e "${GREEN}✅ Appended SVG-PLE sync to existing pre-commit hook${NC}"
    else
        echo -e "${YELLOW}❌ Cancelled - pre-commit hook not modified${NC}"
        exit 0
    fi
else
    # Create new pre-commit hook
    cat > "$HOOK_FILE" <<'HOOK_CONTENT'
#!/usr/bin/env bash
# =============================================================================
# PRE-COMMIT HOOK — SVG-PLE TO-DO AUTO-SYNC
# =============================================================================
# Auto-generated by: infra/scripts/setup-pre-commit-hook.sh
# Purpose: Sync svg-ple-todo.md changes with GitHub Projects before commit
# =============================================================================

echo "🔄 Syncing SVG-PLE To-Do with GitHub Projects..."

# Run auto-sync in once mode
if [ -f "infra/scripts/auto-sync-svg-ple-github.sh" ]; then
    ./infra/scripts/auto-sync-svg-ple-github.sh --once || {
        echo "⚠️  Warning: SVG-PLE sync failed"
        echo "   This is non-blocking - commit will proceed"
        echo "   You can manually sync later with:"
        echo "   ./infra/scripts/auto-sync-svg-ple-github.sh --once"
    }
else
    echo "⚠️  Auto-sync script not found at: infra/scripts/auto-sync-svg-ple-github.sh"
    echo "   Skipping sync..."
fi

echo "✅ Pre-commit checks complete"
exit 0
HOOK_CONTENT
    echo -e "${GREEN}✅ Created new pre-commit hook${NC}"
fi

# Make hook executable
chmod +x "$HOOK_FILE"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ Pre-commit hook installed successfully!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "What happens now:"
echo "  1. Edit infra/docs/svg-ple-todo.md"
echo "  2. Mark tasks with [x] as complete"
echo "  3. git add + git commit"
echo "  4. Pre-commit hook auto-syncs with GitHub Projects"
echo "  5. Corresponding GitHub Issues close automatically"
echo ""
echo "Hook location: .git/hooks/pre-commit"
echo ""
echo -e "${YELLOW}💡 TIP: To skip the hook for a specific commit:${NC}"
echo "   git commit --no-verify"
echo ""
echo -e "${BLUE}Test the hook now:${NC}"
echo "   ./infra/scripts/auto-sync-svg-ple-github.sh --once"
echo ""
