name: Feature Request
description: Suggest a new feature for Barton Outreach Core
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
projects: ["djb258/barton-outreach-core"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature for Barton Outreach Core!

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature relate to?
      options:
        - Company Hub (company_hub.py)
        - People Node Spoke
        - DOL Node Spoke
        - Email Verification SubWheel
        - BIT Engine
        - Pipeline Engine
        - New Spoke (Blog/Talent/Outreach)
        - Enrichment Pipeline
        - Neon Database
        - GitHub Actions / CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: hub-spoke
    attributes:
      label: Hub/Spoke Location
      description: Where in the Bicycle Wheel architecture does this feature belong?
      options:
        - Company Hub (Master Node)
        - People Node Spoke
        - DOL Node Spoke
        - Blog Node Spoke (New)
        - Talent Flow Spoke (New)
        - BIT Engine Spoke
        - Outreach Spoke (New)
        - New SubWheel
        - New Failure Spoke
        - Cross-Spoke Feature
        - Not Applicable
    validations:
      required: true

  - type: dropdown
    id: altitude
    attributes:
      label: CTB Altitude
      description: At what altitude should this feature operate?
      options:
        - 40k ft - Strategic/Vision
        - 20k ft - Architecture/Integration
        - 10k ft - Implementation/Code
        - 5k ft - Data/Database
        - Ground - Operations/DevOps
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of the feature
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: What problem does this solve?
      placeholder: Describe the use case or problem this feature addresses
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: How should this feature be implemented?
      placeholder: |
        Suggest an approach following Bicycle Wheel Doctrine:
        - Which hub/spoke owns this?
        - What tools are needed?
        - What failure modes should be handled?
    validations:
      required: false

  - type: checkboxes
    id: integration
    attributes:
      label: Integration Impact
      description: Which integrations will this affect?
      options:
        - label: Neon PostgreSQL Database
        - label: MillionVerifier (Email Verification)
        - label: Firecrawl (Web Scraping)
        - label: Apify (LinkedIn)
        - label: GitHub Actions
        - label: Composio MCP Server
        - label: None

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
        - P4 - Nice to have
    validations:
      required: true
