# Node 1 Orchestration - Company DB (30k Altitude)
# Garage-MCP + sub-agents configuration (build-only)

version: "1.0"
node: "node-1-company-db"
altitude: "30k"
mode: "build-only"

# Main orchestrator configuration
orchestrator:
  id: "company-db-orchestrator"
  name: "Company Database Orchestrator"
  description: "Manages company ingestion and slot creation at 30k altitude"
  
  capabilities:
    - "CSV/Apollo data ingestion"
    - "Company UID generation"
    - "Slot creation (CEO/CFO/HR)"
    - "Idempotent operations"
    - "Dead-letter handling"

# Sub-agents declaration
agents:
  - id: "ingestor-agent"
    name: "Data Ingestor Agent"
    type: "input"
    responsibilities:
      - "Parse CSV/Apollo exports"
      - "Validate company data"
      - "Queue for processing"
    config:
      batch_size: 100
      retry_attempts: 3
      dead_letter_enabled: true

  - id: "uid-generator-agent"
    name: "UID Generator Agent"
    type: "processor"
    responsibilities:
      - "Generate company UIDs (CO-YYYYMMDD-######)"
      - "Generate slot UIDs (SL-<company>-<role>)"
      - "Ensure uniqueness"
    config:
      sequence_cache: true
      conflict_resolution: "skip"

  - id: "slot-creator-agent"
    name: "Slot Creator Agent"
    type: "processor"
    responsibilities:
      - "Create 3 slots per company"
      - "Assign roles (CEO/CFO/HR)"
      - "Link to company UID"
    config:
      roles:
        - "CEO"
        - "CFO"
        - "HR"
      slots_per_company: 3

  - id: "database-writer-agent"
    name: "Database Writer Agent"
    type: "output"
    responsibilities:
      - "Execute insert_company_with_slots()"
      - "Handle transactions"
      - "Log operations"
    config:
      connection_pool_size: 10
      transaction_timeout: 30
      log_level: "info"

# Workflow definition
workflow:
  stages:
    - name: "ingestion"
      agent: "ingestor-agent"
      input: "csv_file_path"
      output: "validated_companies"
      error_handling: "dead_letter"

    - name: "uid_generation"
      agent: "uid-generator-agent"
      input: "validated_companies"
      output: "companies_with_uids"
      error_handling: "retry"

    - name: "slot_creation"
      agent: "slot-creator-agent"
      input: "companies_with_uids"
      output: "companies_with_slots"
      error_handling: "rollback"

    - name: "persistence"
      agent: "database-writer-agent"
      input: "companies_with_slots"
      output: "success_log"
      error_handling: "transaction"

# Error handling
error_handling:
  dead_letter:
    table: "marketing.dead_letter_queue"
    retention_days: 30
    
  retry:
    max_attempts: 3
    backoff_multiplier: 2
    max_backoff_seconds: 300

# Monitoring
monitoring:
  metrics:
    - "companies_processed"
    - "slots_created"
    - "errors_encountered"
    - "processing_time_ms"
  
  alerts:
    - type: "threshold"
      metric: "error_rate"
      threshold: 0.05
      action: "notify"

# Build configuration (no runtime)
build:
  artifacts:
    - "schema/001_init.sql"
    - "ingestor/seed.sample.csv"
  
  tests:
    - "uid_generation_test"
    - "slot_creation_test"
    - "idempotency_test"
  
  ci_checks:
    - "ddl-validate"
    - "orbt-check"
    - "lint"